/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author p1805797
 */
public class Accueil extends javax.swing.JFrame {

    /**
     * Creates new form Application
     */
    public Accueil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAccueil = new javax.swing.JButton();
        jButtonCreerMatch = new javax.swing.JButton();
        jButtonCreerEntrainement = new javax.swing.JButton();
        jButtonSaisirVainq = new javax.swing.JButton();
        jButtonInvJoueur = new javax.swing.JButton();
        jButtonQuitterApp = new javax.swing.JButton();
        jLabelLogo = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);

        jButtonAccueil.setText("Accueil");
        jButtonAccueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAccueilActionPerformed(evt);
            }
        });

        jButtonCreerMatch.setText("Créer Match");
        jButtonCreerMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreerMatchActionPerformed(evt);
            }
        });

        jButtonCreerEntrainement.setText("Créer Entrainement");
        jButtonCreerEntrainement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreerEntrainementActionPerformed(evt);
            }
        });

        jButtonSaisirVainq.setText("Saisir vainqueur");
        jButtonSaisirVainq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaisirVainqActionPerformed(evt);
            }
        });

        jButtonInvJoueur.setText("Inviter Joueur");
        jButtonInvJoueur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInvJoueurActionPerformed(evt);
            }
        });

        jButtonQuitterApp.setText("Quitter l'application");
        jButtonQuitterApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitterAppActionPerformed(evt);
            }
        });

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        jLabelLogo.setAlignmentY(0.0F);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Bienvenue sur l'application Open Parc");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAccueil)
                            .addComponent(jButtonCreerMatch)
                            .addComponent(jButtonCreerEntrainement))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addComponent(jLabelLogo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonInvJoueur)
                            .addComponent(jButtonQuitterApp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSaisirVainq)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAccueil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCreerMatch)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCreerEntrainement)
                        .addGap(11, 11, 11))
                    .addComponent(jLabelLogo))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jButtonSaisirVainq)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonInvJoueur))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jButtonQuitterApp)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAccueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAccueilActionPerformed
        this.setVisible(true);
    }//GEN-LAST:event_jButtonAccueilActionPerformed

    private void jButtonCreerMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreerMatchActionPerformed
        this.setVisible(false);
        CreerMatch creerMatch = new CreerMatch(this);
        creerMatch.setVisible(true);
    }//GEN-LAST:event_jButtonCreerMatchActionPerformed

    private void jButtonCreerEntrainementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreerEntrainementActionPerformed
        this.setVisible(false);
        CreerEntrainement creerEntrainement = new CreerEntrainement(this);
        creerEntrainement.setVisible(true);
    }//GEN-LAST:event_jButtonCreerEntrainementActionPerformed

    private void jButtonSaisirVainqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaisirVainqActionPerformed
        this.setVisible(false);
        SaisirVainqueur saisirVainqueur = new SaisirVainqueur(this);
        saisirVainqueur.setVisible(true);
    }//GEN-LAST:event_jButtonSaisirVainqActionPerformed

    private void jButtonInvJoueurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInvJoueurActionPerformed
        this.setVisible(false);
        InvJoueur invJoueur = new InvJoueur(this);
        invJoueur.setVisible(true);
    }//GEN-LAST:event_jButtonInvJoueurActionPerformed

    private void jButtonQuitterAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitterAppActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonQuitterAppActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAccueil;
    private javax.swing.JButton jButtonCreerEntrainement;
    private javax.swing.JButton jButtonCreerMatch;
    private javax.swing.JButton jButtonInvJoueur;
    private javax.swing.JButton jButtonQuitterApp;
    private javax.swing.JButton jButtonSaisirVainq;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
